version: "3.8"

x-common-environment: &environment
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${DB_NAME}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}

services:
    notification:
        environment: *environment

    db:
        environment: *environment
