version: "3.8"

services:
    notification:
        image: golang
        command: sleep infinity
        volumes:
            - ./:/app
        ports:
            - "${NOTIFICATION_PORT_TARGET}:8080"
        networks:
            - net
        depends_on:
            -   db

    db:
        platform: linux/x86_64
        image: postgres
        restart: always
        ports:
            - "5442:5432"
        networks:
            - net

networks:
    net:
        name: ${NETWORK_NAME}
        driver: bridge